# Generated by Django 6.0.2 on 2026-02-17 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0002_alter_contestant_options_position_and_more'),
        ('elections', '0001_initial'),
        ('votes', '0002_alter_vote_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vote',
            name='votes_vote_electio_61924e_idx',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='votes_vote_user_id_766d90_idx',
        ),
        migrations.AddField(
            model_name='vote',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='contestants.position'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'election', 'position')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election', 'position', 'contestant'], name='votes_vote_electio_00e1c1_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user', 'election', 'position'], name='votes_vote_user_id_6918b9_idx'),
        ),
    ]
