# Generated by Django 6.0.2 on 2026-02-17 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0001_initial'),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestant',
            options={'ordering': ['election', 'position', 'order', 'name'], 'verbose_name': 'Contestant', 'verbose_name_plural': 'Contestants'},
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='elections.election')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['election', 'order', 'title'],
                'unique_together': {('election', 'title')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contestant',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='contestants.position'),
        ),
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together={('election', 'position', 'name')},
        ),
    ]
