# Generated by Django 6.0.2 on 2026-03-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='visible_to_voters',
            field=models.BooleanField(default=False),
        ),
    ]
