# Generated by Django 6.0.2 on 2026-02-18 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_unique_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterIDRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('used', 'Used'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_voter_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voter ID Registry',
                'verbose_name_plural': 'Voter ID Registry',
                'ordering': ['-created_at'],
            },
        ),
    ]
